"""Generate signup project from analysis.json spec."""

from __future__ import annotations

import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent
BOILER = ROOT / "boilerplate"


def _py_str(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def _build_payload_block(fields: dict) -> str:
    lines = ["        payload = {"]
    for _fk, spec in fields.items():
        key = spec.get("key", _fk)
        ftype = spec.get("type", "static")
        if ftype == "random_name":
            lines.append(f'            {_py_str(key)}: name,')
        elif ftype == "e164_plus":
            lines.append(f'            {_py_str(key)}: phone,')
        elif ftype == "static_bool":
            val = "True" if spec.get("value") else "False"
            lines.append(f'            {_py_str(key)}: {val},')
        else:
            lines.append(f'            {_py_str(key)}: {_py_str(spec.get("value", ""))},')
    lines.append("        }")
    return "\n".join(lines)


def _build_success_check(success: dict) -> str:
    status = success.get("http_status", 200)
    jkey = success.get("json_key")
    jval = success.get("json_equals")
    parts = [f"        if r.status_code == {status}:"]
    if jkey:
        parts.append("            try:")
        parts.append("                data = r.json()")
        if jval is True:
            parts.append(f'                if data.get({_py_str(jkey)}) is True:')
        elif jval is False:
            parts.append(f'                if data.get({_py_str(jkey)}) is False:')
        elif jval is not None:
            parts.append(f'                if data.get({_py_str(jkey)}) == {_py_str(jval)}:')
        else:
            parts.append(f'                if {_py_str(jkey)} in data:')
        parts.append('                    return True, "success"')
        parts.append('                return False, str(data.get("message") or data)[:120]')
        parts.append("            except json.JSONDecodeError:")
        parts.append('                if "success" in body.lower():')
        parts.append('                    return True, body[:80]')
    else:
        parts.append('            return True, "HTTP ok"')
    parts.append('        if "cloudflare" in body.lower() or r.status_code == 403:')
    parts.append('            return False, f"Cloudflare block HTTP {r.status_code}"')
    parts.append('        return False, body[:120] or f"HTTP {r.status_code}"')
    return "\n".join(parts)


def generate_main_py(spec: dict) -> str:
    prefix = spec.get("env_prefix", "SIG_")
    site = spec["site_base"].rstrip("/")
    signup_path = spec.get("signup_path", "/")
    api_path = spec.get("api_path", "/api/submit")
    if not api_path.startswith("/"):
        api_path = "/" + api_path
    fields = spec.get("fields", {})
    success = spec.get("success", {})
    warmup = spec.get("warmup_get", True)
    warmup_every = spec.get("warmup_every", 25)
    content_type = spec.get("content_type", "application/json")
    site_name = spec.get("site_name", spec.get("project_name", "Signup"))
    flow = spec.get("flow_type", "signup")

    consent_const = ""
    consent_key = None
    for fk, fs in fields.items():
        if fs.get("key") in ("consentText", "consent_text") or "consent" in fk.lower() and fs.get("type") == "static":
            consent_const = f'\nCONSENT = {_py_str(fs.get("value", ""))}\n'
            consent_key = fs.get("key")
            break
    if not consent_const and spec.get("consent_snippets"):
        consent_const = f'\nCONSENT = {_py_str(spec["consent_snippets"][0])}\n'

    payload_block = _build_payload_block(fields)
    success_block = _build_success_check(success)

    warmup_code = ""
    if warmup:
        warmup_code = f"""
    def warmup(self) -> None:
        self._req("GET", SIGNUP_PAGE, headers={{"Accept": "text/html,*/*"}})
"""
        submit_preamble = f"""
        self._req_count += 1
        if self._req_count == 1 or self._req_count % {warmup_every} == 0:
            self.warmup()
"""
    else:
        warmup_code = ""
        submit_preamble = ""

    post_kw = "json=payload" if "json" in content_type else "data=payload"

    return f'''#!/usr/bin/env python3
"""
{site_name} — {flow} (Matrix numbers, 1x each).
Auto-generated by script_builder_agent.
"""

from __future__ import annotations

import json
import os
import random
import re
import sys
import time
from datetime import datetime
from pathlib import Path

import requests
from requests.exceptions import ConnectionError as ReqConnErr, Timeout as ReqTimeout

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

import matrix_client  # noqa: E402
from progress_store import ProgressStore  # noqa: E402
from proxy_utils import format_proxy_line, load_proxies_from_file, parse_proxy_for_requests, proxy_fingerprint  # noqa: E402

SCRIPT_DIR = ROOT
LOG_DIR = SCRIPT_DIR / "logs"
RESULTS = SCRIPT_DIR / "signups.json"
DONE_FILE = SCRIPT_DIR / "completed_phones.txt"
PROXY_FILE = SCRIPT_DIR / "proxies.txt"
PROXY_PARENT = SCRIPT_DIR.parent / "proxies.txt"

SITE = {_py_str(site)}
SIGNUP_PAGE = f"{{SITE}}{signup_path if signup_path.startswith('/') else '/' + signup_path}"
API = f"{{SITE}}{api_path}"

{consent_const}
NAMES = ("Hamad", "Ahmad", "Sarah", "James", "Emma", "Omar", "Lisa", "David", "Maria", "Hassan")
_NET = (ReqConnErr, ReqTimeout, ConnectionError, OSError)


def load_env() -> None:
    for p in (SCRIPT_DIR / ".env", SCRIPT_DIR.parent / ".env"):
        if not p.exists():
            continue
        for line in p.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, _, v = line.partition("=")
            os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))


load_env()

WORKER_ID = int(os.getenv("{prefix}WORKER_ID", "0") or "0")
WORKER_TOTAL = max(1, int(os.getenv("{prefix}WORKER_TOTAL", "1") or "1"))
DELAY = float(os.getenv("{prefix}DELAY", "0.15"))
RETRIES = int(os.getenv("{prefix}RETRIES", "2"))
USE_PROXY = os.getenv("{prefix}USE_PROXY", "0").strip().lower() in ("1", "true", "yes", "on")
WARMUP_EVERY = max(1, int(os.getenv("{prefix}WARMUP_EVERY", "{warmup_every}") or "{warmup_every}"))


def log(msg: str) -> None:
    line = f"[{{datetime.now().strftime('%H:%M:%S')}}] [W{{WORKER_ID}}] {{msg}}"
    print(line, flush=True)
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    with open(LOG_DIR / f"worker_{{WORKER_ID}}.log", "a", encoding="utf-8") as f:
        f.write(line + "\\n")


def phone_plus(digits: str) -> str:
    d = re.sub(r"\\D", "", digits)
    return f"+{{d}}"


def shard(entries: list[tuple[str, str]]) -> list[tuple[str, str]]:
    return [e for i, e in enumerate(entries) if i % WORKER_TOTAL == WORKER_ID]


def load_proxies() -> list[dict]:
    if not USE_PROXY:
        return []
    path = PROXY_FILE if PROXY_FILE.exists() else PROXY_PARENT
    if not path.exists():
        return []
    seen: set[str] = set()
    out: list[dict] = []
    for px in load_proxies_from_file(path):
        fp = proxy_fingerprint(px)
        if fp in seen:
            continue
        seen.add(fp)
        out.append(px)
    return out


class SignupClient:
    def __init__(self, proxy_line: str | None = None):
        self.s = requests.Session()
        self.s.headers.update({{
            "User-Agent": (
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                "(KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36"
            ),
            "Accept-Language": "en-US,en;q=0.9",
        }})
        if proxy_line:
            px = parse_proxy_for_requests(proxy_line)
            self.s.proxies = {{"http": px, "https": px}}
        self._req_count = 0

    def _req(self, method: str, url: str, **kw) -> requests.Response:
        err = None
        for i in range(1, RETRIES + 1):
            try:
                return self.s.request(method, url, timeout=30, **kw)
            except _NET as e:
                err = e
                time.sleep(i * 0.5)
        raise err  # type: ignore
{warmup_code}
    def submit(self, name: str, phone: str) -> tuple[bool, str]:
{submit_preamble}
{payload_block}
        headers = {{
            "Accept": "*/*",
            "Content-Type": {_py_str(content_type)},
            "Origin": SITE,
            "Referer": SIGNUP_PAGE,
            "Sec-Fetch-Dest": "empty",
            "Sec-Fetch-Mode": "cors",
            "Sec-Fetch-Site": "same-origin",
        }}
        r = self._req("{spec.get('method', 'POST')}", API, headers=headers, {post_kw})
        body = r.text or ""
{success_block}


def save_row(row: dict) -> None:
    rows = []
    if RESULTS.exists():
        try:
            rows = json.loads(RESULTS.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            pass
    rows.append(row)
    RESULTS.write_text(json.dumps(rows, indent=2), encoding="utf-8")


def main() -> None:
    log("=== {site_name} | 1x per Matrix number ===")
    progress = ProgressStore(DONE_FILE)

    proxies = load_proxies()
    if USE_PROXY and not proxies:
        log("ERROR: {prefix}USE_PROXY=1 but no proxies.txt")
        return

    all_nums = matrix_client.fetch_all(force=True)
    mine = shard(all_nums)
    pending = [(n, r) for n, r in mine if not progress.is_done(n)]

    log(f"Matrix total={{len(all_nums)}} | shard={{len(mine)}} | pending={{len(pending)}}")
    if not pending:
        log("Nothing to do.")
        return

    proxy_idx = WORKER_ID
    ok_n = 0

    for idx, (digits, rng) in enumerate(pending, 1):
        name = random.choice(NAMES)
        phone = phone_plus(digits)
        proxy_line = None
        if proxies:
            proxy_line = format_proxy_line(proxies[proxy_idx % len(proxies)])
            proxy_idx += 1

        log(f"[{{idx}}/{{len(pending)}}] {{name}} | {{phone}} | {{rng}}")
        ok, msg = False, ""
        try:
            client = SignupClient(proxy_line)
            ok, msg = client.submit(name, phone)
        except Exception as e:
            msg = f"{{type(e).__name__}}: {{e}}"

        save_row({{
            "time": datetime.now().isoformat(),
            "worker": WORKER_ID,
            "success": ok,
            "name": name,
            "phone": phone,
            "range": rng,
            "message": msg,
        }})

        if ok:
            progress.mark_done(digits)
            ok_n += 1
            log(f"   OK ({{ok_n}}/{{len(pending)}})")
        else:
            log(f"   FAIL: {{msg}}")

        if idx < len(pending):
            time.sleep(DELAY)

    log(f"DONE worker {{WORKER_ID}}: {{ok_n}}/{{len(pending)}}")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        log("Stopped.")
'''


def _patch_matrix_client(content: str, prefix: str) -> str:
    if not prefix.endswith("_"):
        prefix = prefix + "_"
    return content.replace("CCC_", prefix)


def scaffold_project(spec: dict, out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    prefix = spec.get("env_prefix", "SIG_")
    proj = spec.get("project_name", "site")

    main_name = "signup.py"
    (out_dir / main_name).write_text(generate_main_py(spec), encoding="utf-8")

    for fname in ("matrix_client.py", "progress_store.py", "proxy_utils.py"):
        src = BOILER / fname
        if not src.exists():
            src = Path(__file__).resolve().parent.parent / "clutchcity_signup" / fname
        text = src.read_text(encoding="utf-8")
        if fname == "matrix_client.py":
            text = _patch_matrix_client(text, prefix.rstrip("_"))
        (out_dir / fname).write_text(text, encoding="utf-8")

    (out_dir / "requirements.txt").write_text("requests>=2.28.0\n", encoding="utf-8")
    (out_dir / ".gitattributes").write_text("* text=auto eol=lf\n*.sh text eol=lf\n", encoding="utf-8")

    env_example = f"""# Matrix panel
MATRIX_USER=
MATRIX_PASS=

# Optional: {prefix}PHONE_PREFIX=6011
# {prefix}USE_PROXY=0
# {prefix}DELAY=0.15
# {prefix}WORKER_ID=0
# {prefix}WORKER_TOTAL=1
"""
    (out_dir / ".env.example").write_text(env_example, encoding="utf-8")

    run_sh = f"""#!/bin/bash
DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DIR" || exit 1
PY="$DIR/venv/bin/python"
[ -x "$PY" ] || PY="python3"
exec "$PY" {main_name}
"""
    (out_dir / "run.sh").write_text(run_sh, encoding="utf-8")

    p = prefix.rstrip("_")
    workers_sh = f"""#!/bin/bash
DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DIR" || exit 1
PY="$DIR/venv/bin/python"
[ -x "$PY" ] || PY="python3"
mkdir -p logs
TOTAL=${{WORKERS:-20}}
for i in $(seq 0 $((TOTAL - 1))); do
  {p}_WORKER_ID=$i {p}_WORKER_TOTAL=$TOTAL nohup "$PY" {main_name} >> "logs/worker_${{i}}.log" 2>&1 &
done
echo "Started $TOTAL workers."
"""
    (out_dir / "start_20_workers.sh").write_text(workers_sh, encoding="utf-8")

    (out_dir / "analysis.json").write_text(json.dumps(spec, indent=2), encoding="utf-8")
    (out_dir / "logs").mkdir(exist_ok=True)
